package com.imrainbow.popularmovies.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.imrainbow.popularmovies.dao.Favorite;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "FAVORITE".
*/
public class FavoriteDao extends AbstractDao<Favorite, Long> {

    public static final String TABLENAME = "FAVORITE";

    /**
     * Properties of entity Favorite.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Release_date = new Property(2, String.class, "release_date", false, "RELEASE_DATE");
        public final static Property Vote_average = new Property(3, Float.class, "vote_average", false, "VOTE_AVERAGE");
        public final static Property Overview = new Property(4, String.class, "overview", false, "OVERVIEW");
        public final static Property Poster_path = new Property(5, String.class, "poster_path", false, "POSTER_PATH");
    };


    public FavoriteDao(DaoConfig config) {
        super(config);
    }
    
    public FavoriteDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"FAVORITE\" (" + //
                "\"ID\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"RELEASE_DATE\" TEXT," + // 2: release_date
                "\"VOTE_AVERAGE\" REAL," + // 3: vote_average
                "\"OVERVIEW\" TEXT," + // 4: overview
                "\"POSTER_PATH\" TEXT);"); // 5: poster_path
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"FAVORITE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Favorite entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String release_date = entity.getRelease_date();
        if (release_date != null) {
            stmt.bindString(3, release_date);
        }
 
        Float vote_average = entity.getVote_average();
        if (vote_average != null) {
            stmt.bindDouble(4, vote_average);
        }
 
        String overview = entity.getOverview();
        if (overview != null) {
            stmt.bindString(5, overview);
        }
 
        String poster_path = entity.getPoster_path();
        if (poster_path != null) {
            stmt.bindString(6, poster_path);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Favorite readEntity(Cursor cursor, int offset) {
        Favorite entity = new Favorite( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // release_date
            cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3), // vote_average
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // overview
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // poster_path
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Favorite entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setRelease_date(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setVote_average(cursor.isNull(offset + 3) ? null : cursor.getFloat(offset + 3));
        entity.setOverview(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setPoster_path(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Favorite entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Favorite entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
