package com.imrainbow.popularmovies.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.os.Parcel;
import android.os.Parcelable;

// KEEP INCLUDES END

/**
 * Entity mapped to table "MOVIE_ENTITY".
 */
public class MovieEntity implements Parcelable {

    private Long id;
    private String title;
    private String release_date;
    private Float vote_average;
    private String overview;
    private String poster_path;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public MovieEntity() {
    }

    public MovieEntity(Long id) {
        this.id = id;
    }

    public MovieEntity(Long id, String title, String release_date, Float vote_average, String overview, String poster_path) {
        this.id = id;
        this.title = title;
        this.release_date = release_date;
        this.vote_average = vote_average;
        this.overview = overview;
        this.poster_path = poster_path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getRelease_date() {
        return release_date;
    }

    public void setRelease_date(String release_date) {
        this.release_date = release_date;
    }

    public Float getVote_average() {
        return vote_average;
    }

    public void setVote_average(Float vote_average) {
        this.vote_average = vote_average;
    }

    public String getOverview() {
        return overview;
    }

    public void setOverview(String overview) {
        this.overview = overview;
    }

    public String getPoster_path() {
        return poster_path;
    }

    public void setPoster_path(String poster_path) {
        this.poster_path = poster_path;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeString(this.title);
        dest.writeString(this.release_date);
        dest.writeValue(this.vote_average);
        dest.writeString(this.overview);
        dest.writeString(this.poster_path);
    }

    protected MovieEntity(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.title = in.readString();
        this.release_date = in.readString();
        this.vote_average = (Float) in.readValue(Float.class.getClassLoader());
        this.overview = in.readString();
        this.poster_path = in.readString();
    }

    public static final Parcelable.Creator<MovieEntity> CREATOR = new Parcelable.Creator<MovieEntity>() {
        public MovieEntity createFromParcel(Parcel source) {
            return new MovieEntity(source);
        }

        public MovieEntity[] newArray(int size) {
            return new MovieEntity[size];
        }
    };
    // KEEP METHODS END
}
